/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Paneles;

import Controlador.ControladorAsignacion;
import Modelo.Vehiculo;
import Vista.Menu;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author roy-j
 */
public class Administracion extends javax.swing.JFrame {

    public ControladorAsignacion controlador = Menu.objControlador;
    private static final DateTimeFormatter HOUR_FORMATTER = DateTimeFormatter.ofPattern("HH:mm");

    public Administracion() {
        initComponents();
        mostrarEspacios();

    }

private void mostrarEspacios() {
    adm.removeAll();  
    ArrayList<Vehiculo> espacios = controlador.getSpaces();

    JPanel panelEspacios = new JPanel();
    panelEspacios.setLayout(new GridLayout(0, 1, 10, 10)); // 1 columna por fila
    panelEspacios.setBackground(Color.white);

    // Intentar cargar las imágenes
    ImageIcon imagenOriginal = new ImageIcon(getClass().getResource("/Recursos/Imagenes/car.png")); 
    Image imagenEscalada = imagenOriginal.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
    ImageIcon imagen = new ImageIcon(imagenEscalada);
    
    ImageIcon imgCamapanaRoja = new ImageIcon(getClass().getResource("/Recursos/Imagenes/Campana Normal.png")); 
    ImageIcon imgcampanaNormal = new ImageIcon(getClass().getResource("/Recursos/Imagenes/Campana Roja.png")); 
    
    ImageIcon imgSearch = new ImageIcon(getClass().getResource("/Recursos/Imagenes/search.png"));
    Image imagenEscaladaimgSearch = imgSearch.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
    
    for (int i = 0; i < 20; i++) {
        JPanel panelEspacio = new JPanel(new BorderLayout());
        panelEspacio.setBorder(BorderFactory.createTitledBorder("Espacio " + (i + 1)));
        panelEspacio.setBackground(Color.white); // Fondo de panel

        // Crear un JLabel con la imagen a la izquierda y el texto a la derecha
        JLabel label = new JLabel();
        label.setIcon(imagen);  // Colocar la imagen en el JLabel
        label.setHorizontalAlignment(JLabel.LEFT);  // Alinear la imagen a la izquierda
        label.setVerticalAlignment(JLabel.CENTER);  // Centrar verticalmente
        label.setFont(new java.awt.Font("Segoe Print", 2, 18));

        // Crear un JLabel para la segunda imagen (labelICON)
        JLabel labelICON = new JLabel();
        JLabel search = new JLabel();
        
        if (espacios.get(i).isOccupied()) {
            label.setText("         Ocupado por " + espacios.get(i).getPlaca()+"                  ");
            Image imgr = imgcampanaNormal.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
            ImageIcon imgCp = new ImageIcon(imgr);
            ImageIcon imgSE = new ImageIcon(imagenEscaladaimgSearch);
            labelICON.setIcon(imgCp);
            search.setIcon(imgSE);  // Imagen de búsqueda para espacio ocupado
            
        } else {
            label.setText("                         Libre                       ");
            Image imgr = imgCamapanaRoja.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
            ImageIcon imgCp = new ImageIcon(imgr);
             ImageIcon imgSE = new ImageIcon(imagenEscaladaimgSearch);
            labelICON.setIcon(imgCp);
            search.setIcon(imgSE);  // No mostrar imagen de búsqueda para espacio libre
        }

        // Crear un panel para contener los JLabels
        JPanel contenidoPanel = new JPanel(new BorderLayout());
        contenidoPanel.setBackground(Color.white);
        contenidoPanel.add(label, BorderLayout.WEST); 
        contenidoPanel.add(labelICON, BorderLayout.CENTER);
        contenidoPanel.add(search, BorderLayout.EAST);  // Añadir la tercera imagen a la derecha

        // Añadir el panel contenido al panelEspacio
        panelEspacio.add(contenidoPanel, BorderLayout.CENTER);
        panelEspacios.add(panelEspacio);
    }

    JScrollPane scrollPane = new JScrollPane(panelEspacios);
    scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

    adm.setLayout(new BorderLayout());
    adm.add(scrollPane);

    adm.revalidate();  // Actualizar el diseño
    adm.repaint();   
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Administracion = new javax.swing.JPanel();
        Actualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        adm = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Administracion.setBackground(new java.awt.Color(255, 255, 255));
        Administracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Actualizar.setBackground(new java.awt.Color(181, 223, 224));
        Actualizar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarMouseClicked(evt);
            }
        });
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        Administracion.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 160, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/car.png"))); // NOI18N
        Administracion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 137, 152));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel1.setText("Administracion de espacios para vehiculos");
        Administracion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 540, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        Administracion.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 694, 26));

        adm.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout admLayout = new javax.swing.GroupLayout(adm);
        adm.setLayout(admLayout);
        admLayout.setHorizontalGroup(
            admLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        admLayout.setVerticalGroup(
            admLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Administracion.add(adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 680, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Administracion, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Administracion, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseClicked
        mostrarEspacios();
    }//GEN-LAST:event_ActualizarMouseClicked

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        mostrarEspacios();
    }//GEN-LAST:event_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    public JPanel getJpanel() {
        return Administracion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Actualizar;
    private javax.swing.JPanel Administracion;
    private javax.swing.JPanel adm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
