/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Paneles;

import Controlador.ControladorAsignacion;
import Vista.Menu;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author roy-j
 */
public class Asignacion extends javax.swing.JFrame {

    ControladorAsignacion controlador = Menu.getObjControlador();

    public Asignacion() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Asignacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        Placa = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        User = new javax.swing.JTextField();
        AsignacionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Asignacion.setBackground(new java.awt.Color(255, 255, 255));
        Asignacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/car.png"))); // NOI18N
        Asignacion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 137, 152));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel4.setText("Asignacion de espacios para vehiculos");
        Asignacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 560, 40));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        Asignacion.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 694, 26));

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 250, 20));

        Placa.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        Placa.setForeground(new java.awt.Color(204, 204, 204));
        Placa.setText("Placa");
        Placa.setToolTipText("");
        Placa.setBorder(null);
        Placa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PlacaMousePressed(evt);
            }
        });
        Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaActionPerformed(evt);
            }
        });
        Asignacion.add(Placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 280, 60));

        jSeparator6.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        Asignacion.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 280, 30));

        User.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        User.setForeground(new java.awt.Color(204, 204, 204));
        User.setText("Nombre Usuario");
        User.setBorder(null);
        User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserMousePressed(evt);
            }
        });
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        Asignacion.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 350, 60));

        AsignacionButton.setBackground(new java.awt.Color(181, 223, 224));
        AsignacionButton.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        AsignacionButton.setText("Asignar");
        AsignacionButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AsignacionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AsignacionButtonMouseClicked(evt);
            }
        });
        AsignacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignacionButtonActionPerformed(evt);
            }
        });
        Asignacion.add(AsignacionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Asignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlacaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlacaMousePressed
        if(Placa.getText().equals("Placa")){
            Placa.setText("");
            Placa.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_PlacaMousePressed

    private void PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlacaActionPerformed

    private void UserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserMousePressed
        if(User.getText().equals("Nombre Usuario")){
            User.setText("");
            User.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_UserMousePressed

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed

    }//GEN-LAST:event_UserActionPerformed

    private void AsignacionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AsignacionButtonMouseClicked
        
        String texto= controlador.AsigarEspacio();
        User.setText("");
        Placa.setText("");
        javax.swing.JOptionPane.showMessageDialog(this, texto);
        controlador.mostrar();
              
        
    }//GEN-LAST:event_AsignacionButtonMouseClicked

    private void AsignacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignacionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsignacionButtonActionPerformed

    public JPanel getJpanel(){
        return Asignacion;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asignacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asignacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel Asignacion;
    public static javax.swing.JButton AsignacionButton;
    public static javax.swing.JTextField Placa;
    public static javax.swing.JTextField User;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
