/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Paneles;

import Controlador.ControladorAsignacion;
import Modelo.InformeVehiculosCSV;
import Modelo.Vehiculo;
import Vista.Menu;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author roy-j
 */
public class Informes extends javax.swing.JFrame {

    /**
     * Creates new form Informes
     */
    
    public ControladorAsignacion controlador = Menu.objControlador;
    public Informes() {
        initComponents();
        
        ImageIcon icono = new ImageIcon(getClass().getResource("/Recursos/Imagenes/Informe.png")); 
        Icon marco = new ImageIcon(icono.getImage().getScaledInstance(iconLabel.getWidth(), iconLabel.getHeight(), Image.SCALE_DEFAULT));
        iconLabel.setIcon(marco);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Informe = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        GenerarInforme = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Informe.setBackground(new java.awt.Color(255, 255, 255));
        Informe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Informe.add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 137, 152));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        Informe.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 694, 26));

        GenerarInforme.setBackground(new java.awt.Color(181, 223, 224));
        GenerarInforme.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        GenerarInforme.setText("Generar Informe");
        GenerarInforme.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GenerarInforme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenerarInformeMouseClicked(evt);
            }
        });
        GenerarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarInformeActionPerformed(evt);
            }
        });
        Informe.add(GenerarInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel1.setText("un informe completo de todos los clientes que ");
        Informe.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel3.setText("Recuerda que en este espacio podras descargar ");
        Informe.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel4.setText("han asignado y liberado un espacio ");
        Informe.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel2.setText("Informe de vehiculos");
        Informe.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 540, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Informe, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Informe, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerarInformeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerarInformeMouseClicked
        
    }//GEN-LAST:event_GenerarInformeMouseClicked

    private void GenerarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarInformeActionPerformed
      
        //Pasar este codigo al modelo y llamarlo desde el controlador
        InformeVehiculosCSV informe = new InformeVehiculosCSV();
         String archivoDestino = "src/Recursos/Informes/Informe.xlsx"; 
         ArrayList<Vehiculo> espacios = controlador.getSpaces();
         
         System.out.println(""+espacios.get(0).getPlaca());
         try {
             informe.generarInformeCSV(espacios, archivoDestino);
         } catch (IOException ex) {
             Logger.getLogger(Informes.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_GenerarInformeActionPerformed

    public JPanel getJpanel(){
        return Informe;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton GenerarInforme;
    public static javax.swing.JPanel Informe;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
