/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Paneles;

import Controlador.ControladorAsignacion;
import Modelo.CambiaPanel;
import Modelo.Vehiculo;
import Vista.Menu;
import static Vista.Menu.PanelPrincipal;
import static Vista.Paneles.Asignacion.Placa;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author roy-j
 */
public class Liberacion extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    
    public ControladorAsignacion controlador = Menu.getObjControlador();

    public Liberacion() {
        initComponents();
       
    // Crear el JScrollPane y agregar Panel_F al JScrollPane
        JScrollPane scrollPane = new JScrollPane(Panel_F);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        // Agregar el JScrollPane al panel Liberacion
        Liberacion.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 520, 260));
        Liberacion.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 340, 50));
        this.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Liberacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        consultarPlaca = new javax.swing.JTextField();
        Consultar = new javax.swing.JButton();
        Panel_F = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Liberacion.setBackground(new java.awt.Color(255, 255, 255));
        Liberacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Imagenes/car.png"))); // NOI18N
        Liberacion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 137, 152));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel1.setText("Liberacion de espacios");
        Liberacion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 330, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        Liberacion.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 694, 26));

        consultarPlaca.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        consultarPlaca.setForeground(new java.awt.Color(204, 204, 204));
        consultarPlaca.setText("Placa");
        consultarPlaca.setToolTipText("");
        consultarPlaca.setBorder(null);
        consultarPlaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                consultarPlacaMousePressed(evt);
            }
        });
        consultarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarPlacaActionPerformed(evt);
            }
        });
        Liberacion.add(consultarPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 300, 50));

        Consultar.setBackground(new java.awt.Color(181, 223, 224));
        Consultar.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Consultar.setText("Consultar");
        Consultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarMouseClicked(evt);
            }
        });
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        Liberacion.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 130, 40));

        Panel_F.setBackground(new java.awt.Color(255, 255, 255));
        Panel_F.setLayout(new javax.swing.BoxLayout(Panel_F, javax.swing.BoxLayout.LINE_AXIS));
        Liberacion.add(Panel_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 520, 260));
        Liberacion.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 340, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Liberacion, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Liberacion, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarPlacaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarPlacaMousePressed
        if(consultarPlaca.getText().equals("Placa")){
            consultarPlaca.setText("");
            consultarPlaca.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_consultarPlacaMousePressed

    private void consultarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarPlacaActionPerformed

    private void ConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarMouseClicked
         
        String placa = consultarPlaca.getText();
        Vehiculo vh = controlador.BuscarPlaca(placa);
        if( vh != null ){
             Factura factura = new Factura();
             factura.datos(vh);
            new CambiaPanel(Panel_F, factura.getJpanel());
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "La placa no se encuentra asignada a ningun espacio");
            consultarPlaca.setText("");
        }
    }//GEN-LAST:event_ConsultarMouseClicked

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
       
        
   
    }//GEN-LAST:event_ConsultarActionPerformed
    
    public JPanel getJpanel(){
            return Liberacion;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Liberacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Liberacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Liberacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Liberacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Liberacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Consultar;
    private javax.swing.JPanel Liberacion;
    private javax.swing.JPanel Panel_F;
    public static javax.swing.JTextField consultarPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
